### ISSUE TITLE
Utilizing Steamworks cloud feature.  

### ISSUE THREAD

**Issue by TJvrDev** [rlabrecque/Steamworks.NET-Test#10]
I've calibrated the Steamworks.net-Test-master project to only generate buttons for the Steam Remote Storage Test &, I'm having issues successfully saving the "message.dat" file. 

I get:
[1331 - RemoteStorageFileWriteAsyncComplete] - k_EResultIOFailure

I've signed up to Steamworks as a developer and payed the fee.
So I have cloud storage ready to be used and i've added my appid to the steam_appid test doc.

Do you have any recommendations on how to successfully save/load using the steamworks cloud?
I'm literally just trying to store a json string for my game.

**Comment by TJvrDev** [comment]
Nevermind I got it, I just needed to put my app id in the Steam Manager.

**Comment by rlabrecque** [comment]
That's actually slightly concerning to me, do you mean in this place specifically?

`SteamAPI.RestartAppIfNecessary(AppId_t.Invalid)`

Because it merely checks if you launched from Steam, if you haven't then it tells you to shutdown and then it relaunches your game. The executable it launches is not necessarily the same one that you were running though, because it only restarts the one that lives under the Steam/SteamApps/common folder.

**Comment by TJvrDev** [comment]
Right, I added it there and in the steam_appid text file.
